### ISSUE TITLE
ボタンの色が変わりません

### ISSUE THREAD

**Issue by webgoto** [binzume/aframe-xylayout#1]
`<a-xybutton color="blue" hoverColor="red" label="Start!" labelColor="black" width="3" height="0.5"></a-xybutton>`
のような指定で使用してもデフォルトの白黒の色になってしまうようです。
ご確認いただけたら幸いです。

**Comment by binzume** [comment]
ご指摘，ありがとうございます．

`color`, `hover-color`, `label-color` 属性が抜けていたので追加しました． commit: https://github.com/binzume/aframe-xylayout/commit/3947afef3004e51d7f0dd3a92add1bc4f838e2b9

あとREADMEに説明が無いのでわかりにくいですが，A-Frameのcomponentのパラメータの命名規則と，タグの属性の命名規則が異なるので，HTMLタグを書くときは`camelCase`ではなく`spinal-case`となります．

他にもcomponentの説明にあるのにタグの属性が登録されていないものが残っている可能性があるので，その場合は以下のように書くと，とりあえずは回避できます (時間があるときにREADME含めて見直しておきます)
`<a-xybutton xybutton="color:blue; hoverColor:red; labelColor:black" label="Start!" width="3" height="0.5"></a-xybutton>`

**Comment by webgoto** [comment]
修正ありがとうございます。
コンポーネントのパラメータと属性での指定は別物なのですね。
aframeの仕組みの理解も深まりました。
ありがとうございます。
